name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  terraform_run:
    runs-on: ubuntu-22.04
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-south-1"
          aws-access-key-id: ${secrets.ACC_KEY}
          aws-secret-access-key: ${secrets.SACC_KEY}
      - uses: actions/checkout@v4
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
      - run: sleep 120s
      - run: terraform destroy -auto-approve
      - run: exit